// Generated by CoffeeScript 1.3.3
(function() {
  var Echo, UglifyJS, app, db, express, port, renderEchoes;

  express = require('express');

  UglifyJS = require('uglify-js');

  db = require('./db');

  Echo = db.Echo;

  app = express(express.logger());

  app.use(express.bodyParser());

  renderEchoes = function(res, echoes) {
    var echo, echoContents;
    echoContents = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = echoes.length; _i < _len; _i++) {
        echo = echoes[_i];
        _results.push(echo.content);
      }
      return _results;
    })();
    res.type('js');
    return res.send(UglifyJS.minify(echoContents.join("\n"), {
      fromString: true
    }).code);
  };

  app.get('/echoes.js', function(req, res) {
    return Echo.find({}, function(err, echoes) {
      return renderEchoes(res, echoes);
    });
  });

  app.get('/echoes/:id.js', function(req, res) {
    var title, type, _ref;
    _ref = req.params, title = _ref.title, type = _ref.type;
    return Echo.findById(req.params.id, function(err, echo) {
      return renderEchoes(res, [echo]);
    });
  });

  app.get('/echoes.json', function(req, res) {
    return Echo.find({}, function(err, echoes) {
      var echo;
      res.type('json');
      return res.send((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = echoes.length; _i < _len; _i++) {
          echo = echoes[_i];
          _results.push(echo.toSlimJSON());
        }
        return _results;
      })());
    });
  });

  app.post('/', function(req, res) {
    var echo;
    echo = null;
    return Echo.find({
      title: req.body.title,
      author: req.body.author
    }, function(err, echoes) {
      if (err) {
        console.error(err);
      }
      echo = echoes[0] || new Echo;
      echo.title = req.body.title;
      echo.author = req.body.author;
      echo.repository = req.body.repository;
      echo.homepage = req.body.homepage;
      echo.type = req.body.type;
      echo.content = req.body.content;
      return echo.save(function(err) {
        if (err) {
          console.error(err);
        }
        res.type('js');
        return res.send(echo.toSlimJSON());
      });
    });
  });

  port = process.env.PORT || 5000;

  app.listen(port, function() {
    return console.log("Listening on " + port);
  });

}).call(this);
